server:
  port: ${PORT:-2333}
  address: 0.0.0.0
  http2:
    enabled: false

spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.17.0"
      snapshot: false
  server:
    password: ${LAVALINK_SERVER_PASSWORD:-youshallnotpass}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    ws:
      path: "/v4/websocket"

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBED
      - WEB_REMIX
      - TVHTML5
      - TVHTML5_EMBED
      - ANDROID
      - IOS

youtube:
  apiKey: ${YOUTUBE_API_KEY:-""}

logging:
  level:
    root: INFO
    lavalink: INFO
